### ISSUE TITLE
Werk aan de winkel

### ISSUE THREAD

**Issue by ThomasMW** [MartijnDevNull/ticketnak#3]
Hey Martijn,

Je hebt mij een tijd geleden aangesproken op Reddit met de vraag of mijn oude bot nog werkte. 
Ik zie dat ze ondertussen aardig wat veranderd hebben, en recentelijk hun api nog hebben aangepast.

Kan je mij een update geven met waar je nu mee bezig zodat ik je kan helpen met een nieuwe commit.
Mocht je een voorkeur hebben voor onze communicatie let me know.

**Comment by noisesfromspace** [comment]
Hey Thomas,

Momenteel zit ik in mijn tentamenweken en heb ik geen tijd om hier aan te werken maar lijkt het me wel leuk om mijn bot weer werkend te maken. Ik hou je op de hoogte als ik er weer aan begin

**Comment by IkenHuub** [comment]
Werkt dus niet helaas.

python ticketnak.py
Traceback (most recent call last):
  File "ticketnak.py", line 100, in <module>
    ticketnak.run()
  File "ticketnak.py", line 90, in run
    self._filter_ticketswap_post(self._get_event_feed())
  File "ticketnak.py", line 48, in _get_event_feed
    return self.graph.get_object(id='{}/feed'.format(self.settings.FB_EVENT_ID), fields='story,updated_time,id')[
  File "/home/domenico/ticketnak/env/lib/python3.4/site-packages/facebook/__init__.py", line 116, in get_object
    return self.request("{0}/{1}".format(self.version, id), args)
  File "/home/domenico/ticketnak/env/lib/python3.4/site-packages/facebook/__init__.py", line 294, in request
    raise GraphAPIError(result)
facebook.GraphAPIError: Unsupported get request. Object with ID '2015237818687629' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

**Comment by IkenHuub** [comment]
Werkt dus niet helaas.

`python ticketnak.py
Traceback (most recent call last):
  File "ticketnak.py", line 100, in <module>
    ticketnak.run()
  File "ticketnak.py", line 90, in run
    self._filter_ticketswap_post(self._get_event_feed())
  File "ticketnak.py", line 48, in _get_event_feed
    return self.graph.get_object(id='{}/feed'.format(self.settings.FB_EVENT_ID), fields='story,updated_time,id')[
  File "/home/ticketnak/env/lib/python3.4/site-packages/facebook/__init__.py", line 116, in get_object
    return self.request("{0}/{1}".format(self.version, id), args)
  File "/home/domenico/ticketnak/env/lib/python3.4/site-packages/facebook/__init__.py", line 294, in request
    raise GraphAPIError(result)
facebook.GraphAPIError: Unsupported get request. Object with ID '2015237818687629' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api`

**Comment by noisesfromspace** [comment]
@IkenHuub na alle commotie tussen Facebook en Cambridge Analytica is de Graph API gelimiteerd voor nieuwe applicaties: https://newsroom.fb.com/news/2018/03/cracking-down-on-platform-abuse/

Tot dit opgelost is zal dit niet werken tenzij je al een bestaande API key hebt die live is en deze resources eerder gebruikt hebt.
